polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('criar_projeto/', views.create_project, name='criar projeto'),
    path('<int:id_projeto>/importar/', views.import_project, name='importar_projeto'),
    path('<int:id_projeto>/editar/', views.project_setup, name='editar_projeto'),
]

project/ctsp/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views
from django.contrib.auth.views import login, logout_then_login

app_name = 'ctsp'

'''
This module provides all our ctsp application urls.
Direct accesses and redirects needs to pass here.
To learn more about the django urls refer to: https://docs.djangoproject.com/en/2.0/ref/urls/
'''

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('welcome_created/', views.CreateProjectView.as_view(),
         name='create_project'),
    path('welcome/<int:pk>/', views.WelcomeProjectView.as_view(),
         name='project_welcome'),
    path('create_sprint/<int:pk>/',
         views.CreateSprintView.as_view(), name='create_sprint'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('create_members/<int:pk>/',
         views.CreateMembers.as_view(), name='create_members'),
    path('register_user/', views.RegisterUser.as_view(), name='register_user'),
    path('login/', views.LogInMember.as_view(), name='login'),
    path('welcome_login/', views.WelcomeLogin.as_view(), name='welcome_login'),
    path('logout/', logout_then_login,
         {'login_url': '/login/'}, name='logout'),
    path('goto_product_backlog', views.ProjectRedirect.as_view(), name='goto_product_backlog'),
    path('product_backlog/<int:pk>/', views.ProductBacklog.as_view(), name='product_backlog'),
    path('assign_members/<int:pk>/', views.AssignMembers.as_view(), name='assign_members')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('ctsp.urls')),
    path('admin/', admin.site.urls),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

project/ctsp/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.core.validators import RegexValidator
from django.contrib.auth.models import User

# Create your models here.

'''
This package creates our Project model, which is the essential definition of our table fields and behaviour.
To learn more about MySQL database modeling refer to: https://dev.mysql.com/doc/workbench/en/wb-getting-started-tutorial-creating-a-model.html
To learn more about Django database models refer to: https://docs.djangoproject.com/en/2.0/topics/db/models/
'''


# class User_Project(models.Model):


class Usuario(models.Model):
    # user information data
    user_name = models.CharField(max_length=128, null=False, blank=False)
    user_name_max_length = user_name.max_length
    user_last_name = models.CharField(max_length=128, null=False, blank=False)
    user_lane_name_max_length = user_last_name.max_length
    user_birthday = models.CharField(max_length=20, null=False, blank=False)
    user_cellphone_number = models.CharField(max_length=15)
    user_habilities = models.CharField(max_length=300)
    user_usuario = models.OneToOneField(
        User, related_name="usuario_relacionado", on_delete='Cascade')

    @property
    def email(self):
        return self.user_usuario.email

    # user logon data
    # user_email = models.EmailField(max_length=128)
    # user_password = models.CharField(max_length=128, null=False)

    class Meta:
        ordering = ('user_name',)

    def __str__(self):
        return self.user_name


class Project(models.Model):
    # project information
    # project_member = models.ManyToManyField(Usuario)
    project_name = models.CharField(max_length=128, null=False, blank=False)
    project_name_max_length = project_name.max_length
    project_start_date = models.DateField(
        default=timezone.now, null=False, blank=False)
    project_final_date = models.DateField(
        default=timezone.now, null=False, blank=False)

    class Meta:
        ordering = ('project_name',)

    def __str__(self):
        return self.project_name


class ProjectUser(models.Model):
    member = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)


class US(models.Model):
    # enum definitions
    USER_STORY = "US"
    EPIC = "EP"
    THEME = "TH"
    us_type_choices = ((USER_STORY, "User Story"), (EPIC, "Epic"), (THEME, "Theme"))

    HIGH = "H"
    MEDIUM = "M"
    LOW = "L"
    us_priority_choices = ((HIGH, "High"), (MEDIUM, "Medium"), (LOW, "Low"))

    # US fields
    us_project = models.ForeignKey(
        Project, on_delete=models.CASCADE)  # many US to one Project

    us_title = models.CharField(max_length=128, null=False, blank=False)
    us_title_max_length = us_title.max_length

    us_estimative = models.PositiveIntegerField(null=False, blank=False)

    us_type = models.CharField(max_length=2, null=False, blank=False, choices=us_type_choices, default=USER_STORY)

    us_priority = models.CharField(max_length=1, null=False, blank=False, choices=us_priority_choices, default=HIGH)

    us_description = models.TextField(max_length=2144, null=False, blank=False)
    us_description_max_length = us_description.max_length

    us_acceptance = models.TextField(max_length=2144, null=False, blank=False)
    us_acceptance_max_length = us_acceptance.max_length

project/ctsp/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import TemplateView, RedirectView
from django.views.generic.base import View
from .forms import ProjectForm, QueryProjectForm, UserForm, USRegister, US
from .models import Project, Usuario, ProjectUser
from itertools import chain
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.functional import cached_property

# Create your views here.

'''
Generic class views are a form of making the application development easier and faster by using pre-made views.
Those views have methods and variables ready for it's cenario.
To learn more about class based views refer to: https://docs.djangoproject.com/en/2.0/ref/class-based-views/
'''


class IndexView(View):
    template_name = 'ctsp/index.html'

    def post(self, request, *args, **kwargs):
        """
        This function receives the post method comming from the IndexView.
        The return is a JSON file returning all the elements of the searched Project.
        To learn about "Q classes" refer to: https://docs.djangoproject.com/en/2.0/topics/db/queries/
        To learn about JSON file structure refer to: https://www.json.org/ and http://json.org/example.html
        """

        if self.request.is_ajax():
            search_text = request.POST.get('search_text')

            try:
                project = Project.objects.filter(
                    Q(project_name__icontains=search_text) | Q(id__icontains=search_text))
            except ValueError:
                project = Project.objects.filter(
                    project_name__icontains=search_text)

            context = []
            for i in range(0, len(project)):
                context.append({
                    'project_pk': project[i].id,
                    'project_name': project[i].project_name,
                    'project_start': project[i].project_start_date,
                    'project_end': project[i].project_final_date,
                })
            return JsonResponse(context, safe=False)

        return render(request, self.template_name)

    def get(self, request):
        form = ProjectForm()
        query = QueryProjectForm()
        context = {'query': query, 'form': form}
        return render(request, self.template_name, context)


class CreatePbacklogView(TemplateView):
    template_name = "ctsp/create_pbacklog.html"


class CreateSprintView(TemplateView):
    template_name = "ctsp/create_sprint.html"


class AssignMembersView(TemplateView):
    template_name = "ctsp/assign_members.html"


class CreateProjectView(View):
    """
    This redirect view is used as a middleware view to creating a unique URL for the project.
    The URL contains the actual database PK for the project which is generated at the momment it is saved.
    This primary key can be encrypted in the future.
    """

    pattern_name = 'project_welcome'

    def get(self, request):
        return render(request, 'ctsp:project_welcome')

    def post(self, request, *args, **kwargs):
        form = ProjectForm(request.POST)
        if form.is_valid():
            print("form valid")
            project = form.save(commit=True)
            return redirect('ctsp:project_welcome', pk=project.pk, permanent=False)

        # return redirect('ctsp:index')


class WelcomeProjectView(TemplateView):
    template_name = 'ctsp/welcome_created.html'

    def get_context_data(self, **kwargs):
        context = super(WelcomeProjectView, self).get_context_data(**kwargs)
        context['project'] = Project.objects.filter(pk=context['pk'])
        return context


class AboutView(TemplateView):
    template_name = 'ctsp/about.html'


class CreateMembers(TemplateView):
    template_name = 'ctsp/create_members.html'


class RegisterUser(View):
    template_name = 'ctsp/register_user.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        form = UserForm(request.POST)

        dados_form = form.data

        if form.is_valid():
            novo_usuario = User.objects.create_user(
                dados_form['nome'], dados_form['email'], dados_form['senha'])
            usuario = Usuario(user_name=dados_form['nome'],
                              user_last_name=dados_form['sobrenome'],
                              user_birthday=dados_form['data'],
                              user_cellphone_number=dados_form['telefone'],
                              user_habilities=dados_form['habilidades'],
                              user_usuario=novo_usuario)

            usuario.save()
            return redirect('ctsp:index')

        return render(request, self.template_name, {"form": form})


class LogInMember(View):
    template_name = 'ctsp/login.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        return redirect("ctsp:welcome_login")


class ProjectRedirect(View):
    template_name = 'ctsp/welcome_login.html'

    def post(self, request):
        pk = request.POST.get("select_project_pk")
        if request.POST.get('_product'):
            return redirect('ctsp:product_backlog', pk=pk)
        if request.POST.get('_team'):
            return redirect('ctsp:assign_members', pk=pk)
        else:
            return render(request, self.template_name)


class AssignMembers(TemplateView):
    template_name = 'ctsp/assign_members.html'

    def get_context_data(self, **kwargs):
        context = super(AssignMembers, self).get_context_data(**kwargs)
        context['users'] = Usuario.objects.all()
        return context

    def post(self, request, **kwargs):
        if self.request.is_ajax():
            proj_pk = super(AssignMembers, self).get_context_data(**kwargs)['pk'];
            user_pk = request.POST['member']

            # just in case...
            user = Usuario.objects.get(id=user_pk)
            print(user.user_name)
            project = Project.objects.get(id=proj_pk)

            instance = ProjectUser(member_id=user_pk, project_id=proj_pk)
            instance.save()
            return JsonResponse({'user': user.user_name, 'project': project.project_name}, safe=False)


class ProductBacklog(TemplateView):
    template_name = 'ctsp/product_backlog.html'

    def get_context_data(self, **kwargs):
        context = super(ProductBacklog, self).get_context_data(**kwargs)
        context['form'] = USRegister()
        return context

    def post(self, request, *args, **kwargs):
        if self.request.is_ajax():
            form = USRegister(request.POST)
            if form.is_valid():
                # create instance to save and check
                instance = form.save(commit=False)
                pk = super(ProductBacklog, self).get_context_data(**kwargs)['pk']
                instance.us_project = Project.objects.get(id=pk)
                form.save()

                # creating feedback dict
                feedback = dict()
                for key in form.cleaned_data:
                    feedback[key] = form.cleaned_data[key]

                return JsonResponse({'feedback': feedback, 'message': 'your US was registered.'}, safe=False)
            else:
                return JsonResponse({'message': 'Check your form inputs'}, safe=False)


class WelcomeLogin(TemplateView):
    template_name = 'ctsp/welcome_login.html'

    # "get_context_data" not needed anymore, substituted by the "projects" function above

    # def get_context_data(self, **kwargs):
    #     context = super(WelcomeLogin, self).get_context_data(**kwargs)
    #     context['projects'] = Project.objects.all()
    #     return context

    @cached_property
    def projects(self):
        return Project.objects.only('project_name', 'pk')

    def post(self, request):
        return render(request, self.template_name)

project/ctsp/templates/ctsp/CadastroPapeis.html
<div class="container">
    <p class="text-center text-primary display-4">Projeto <em>X</em> -  Papéis Scrum</p>
    <p class="text-center">Cadastre/edite aqui os papéis do time Scrum do <span class="text-primary">Projeto <em>X</em></span> .</p>

    <div class="row">
        <div class="col-4"></div>
        <div class="col-5">
            <div class="row">
                <div class="col-6">
                    <p class="text-primary"><strong>Papéis</strong></strong></p>
                </div>
                <div class="col-6">
                    <p class="text-primary"><strong>Usuário</strong></p>
                </div>
            </div>
        </div>
        <div class="col-3"></div>
    </div>

    <div class="row">
        <div class="col-3"></div>
        <div class="col-6 mt-3">
            <form action="#paginarecolherdados" method="post" id="formularioPapeis" name="formPapeis">
                <div class="form-group">

                    <div class="form-group row">
                        <label for="emailScrum" class="col-4">Scrum Master*:</label>
                        <div class="col-3"></div>
                        <div class="col-5">
                            <input class="form-control" name="emailSM" type="email" value="" id="emailScrum" placeholder="email">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="emailProductOwner" class="col-4">Product Owner*:</label>
                        <div class="col-3"></div>
                        <div class="col-5">
                            <input class="form-control" name="emailPO" type="email" value="" id="emailProductOwner" placeholder="email">
                        </div>
                    </div>
                    <p class="text-right text text-muted"><small>*Os papeis de Product Owner e Scrum Master são obrigatórios em um projeto.</small></p>
                    <p class="text-center text-primary display-4">Developers Team</p>

                    <div class="row">
                        <div class="col-2"></div>
                        <div class="col-6">
                            <div class="row">
                                <div class="col-6">
                                    <p class="text-primary"><strong>Especialidade</strong></p>
                                </div>
                                <div class="col-4"></div>
                                <div class="col-2">
                                    <p class="text-primary"><strong>Usuário</strong></p>

                                </div>

                            </div>
                        </div>
                        <div class="col-4"></div>
                    </div>

                    <div class="row">
                        <div class="col-11" id="copia">
                            <div class="form-group row">
                                <div class="form-group col-4">
                                    <select class="form-control" id="Select1">
                                      <option value="Developer Team">Developer Team</option>
                                    </select>
                                  </div>
                                 <div class="col-4"></div>
                                 <div class="form-group col-4">
                                    <input type="email" class="form-control" id="exampleInputEmail1"  placeholder="email">
                                 </div>
                            </div>
                        </div>
                          <div class="col-1">
                            <button type="button" class="btn btn-primary btn-icon btn-custom" id="add">
                                <i class="fas fa-plus-circle fa-10px"></i>
                                Adicionar
                            </button>

                          </div>
                    </div>
                    <div class="row" id="cola"></div>

                </div>
                <div class="row">
                    <div class="col-2"></div>
                    <div class="col-6">
                        <div class="row">
                            <div class="col-6">
                                <button type="button" class="btn  btn-outline-primary">Cancelar</button>
                            </div>
                            <div class="col-2"></div>
                            <div class="col-4">
                                <button type="submit" class="btn btn-primary">Salvar Alterações</button>
                            </div>
                        </div>
                    </div>
                    <div class="4"></div>
                </div>

            </form>
        </div>
        <div class="col-3"></div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        //aqui vai suas funcoes do jquery
        $("#add").click(function() {
            //exampleInputEmail1
            //if (consultaajaxverificandoemail){
            //replica
            //}else{
            //nao replica
            //}

            var input = document.getElementById('#exampleInputEmail1');
            alert(input);
            $('#copia').clone().appendTo('#cola');
            $('#exampleInputEmail1').val('');
        });
    });
</script>

project/ctsp/templates/ctsp/about.html
{% extends 'ctsp/base.html' %}
{% load staticfiles %}

{% block title_block %}
About - CTSP
{% endblock %}

{% block body_block %}
<p>Text</p>
{% endblock %}

project/ctsp/templates/ctsp/base.html
<!DOCTYPE html> {% load staticfiles %}
<html lang="en">

<head>
    <style>
        .query-table {
            font-family: arial, sans-serif;
            border-collapse: revert;
            width: 100%;
        }

        .td,
        .th {
            border: 5px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        .tr {
            background-color: #007bff;
        }
    </style>
    <link rel="stylesheet" href="{% static 'ctsp/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'ctsp/css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'ctsp/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% block head_block %} {% endblock %}
    <title>
        {% block title_block %} Cloud Tool for Scrum Practitioners {% endblock %}
    </title>
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary fixed-top">
        <a class="navbar-brand" href="{% url 'ctsp:index' %}">
            <img src="" width="30" height="30" class="d-inline-block align-top" alt=""> CTSP
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto" id='tabs'>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'ctsp:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ctsp:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ctsp:register_user' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ctsp:login' %}">Login</a>
                </li>


                <li class="nav-item"><a class="nav-link" href="{% url 'ctsp:logout' %}">Logout</a></li>

            </ul>
        </div>
        <script>
            $(document).ready(function () {
                $('li.active').removeClass('active');
                $('a[href="' + location.pathname + '"]').closest('li').addClass('active');
            });
        </script>
    </nav>

    <!-- page specific content -->
    {% block body_block %} {% endblock %}

    <footer class="card-footer text-center bg-primary fixed-bottom">
        <a class="text-light" href="{% url 'ctsp:about' %}">About</a>
        <a class="text-light" href="{% url 'ctsp:index' %}">Home</a>
        {% block footer_block %} {% endblock %}
    </footer>
</body>

</html>

project/ctsp/templates/ctsp/index.html
{% extends 'ctsp/base.html' %} {% load staticfiles %} {% block body_block %} {% block head_block %} {% endblock %}
<!--Botoes no centro da tela-->
<div class="container size">
    <div class="row vertical-align justify-content-center">
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modalCreateProject">
            Create Project
        </button>
        <div class="col-2"></div>
        <button type="button" class="btn btn-lg" data-toggle="modal" data-target="#modalOpenProject">
            Open Project
        </button>
    </div>
</div>

<!--Formulario criar projeto-->
<div id="modalCreateProject" class="modal fade" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Create Project</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <!-- Form code begins -->
            <form action="{% url 'ctsp:create_project' %}" id="create_form" method="post">
                {% csrf_token %} {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
                <div class="modal-body">
                    <div style="padding-bottom: 2vh">
                        <label>Project Name</label>
                        <input type="text" name="project_name" id="id_project_name" maxlength="128" required class="form-control" />
                    </div>

                    <div style="padding-bottom: 2vh">
                        <label>Start date</label>
                        <input type="text" name="project_start_date" required class="form-control control-label" autocomplete="off" placeholder="MM/DD/YYY" id="start_date" />
                    </div>

                    <div style="padding-bottom: 2vh">
                        <label>Final date</label>
                        <input type="text" name="project_final_date" required class="form-control control-label" autocomplete="off" placeholder="MM/DD/YYY" id="final_date" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary" name="submit" form="create_form" data-dismiss="modal-body">Create
                    </button>
                </div>
            </form>
            <!-- Form code ends -->
        </div>
    </div>
</div>

<!--Formulario abrir projeto-->
<div id="modalOpenProject" class="modal fade" role="dialog">
    <div id="modal-show" class="modal modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Open Project</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <!-- Form code begins -->
            <form id="open_form">
                {% csrf_token %}
                <div class="modal-body">
                    {% for hidden in query.hidden_fields %} {{ hidden }} {% endfor %} {% for field in query.visible_fields %}
                    <div style="padding-bottom: 2vh">
                        <label>{{ field.label }}</label>
                        {{ field }}
                    </div>
                    {%endfor%}
                    <table id="project_table" class="query-table td th">
                        <tbody id="table_body">
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <button id="query-go" class="btn btn-primary" type="button">Search</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Scripts -->
<script>
    function preventDate() {
        let start_date = $("#start_date").val();
        let final_date = $("#final_date").val();
        if (final_date < start_date) {
            return false;
        }
        return true;
    }
</script>
<script>
    $("#project_name_or_ID").keypress("click", function (event) {
        if (event.key !== "Enter")
            return;
        $("#query-go").click();
        event.preventDefault();
    });
</script>
<script>
    $(document).ready(function () {
        let date_input = [$('input[id$="_date"]')];
        let ex = $(".bootstrap-iso form");
        let container = ex.length > 0 ? ex.parent() : "body";
        let options = {
            format: 'mm/dd/yyyy',
            container: container,
            todayHighlight: true,
            orientation: "auto right",
            autoclose: true,
        };
        date_input.forEach(function (e) {
            e.datepicker(options);
        })
    });
</script>
<script>
    /*
    The following function use a mix of JQuery and JQuery.Ajax to perform an asynchronous HTTP request.
    Then the queried data is parsed into an HTML table dinamically crating rows.
    To learn more about HTML5 and its DOM elements refer to: https://developer.mozilla.org/en-US/docs/Web/HTML
    To learn more about JQuery refer to: http://api.jquery.com/
    To learn more about JQuery.Ajax refer to: http://api.jquery.com/category/ajax/
    */
    $("#query-go").on("click", function () {
        let search_text = $(project_name_or_ID).val();
        $.ajax({
            type: 'post',
            data: {
                'search_text': search_text,
                'csrfmiddlewaretoken': '{{ csrf_token }}',
            },
            dataType: 'json',
            success: function (data) {
                $("tr").remove();
                $("caption").remove();
                if (data.length) {
                    $("table")
                        .append("<caption>" + 'Total of ' + data.length + ' projects found' + "</caption>")
                        .append("<tr class='tr text-light'>" +
                            "<th>ID</th>" +
                            "<th>Name</th>" +
                            "<th>Start Date</th>" +
                            "<th>End Date</th>" +
                            "</tr>");
                } else {
                    $("table").append("<caption class='text-danger'>No projects were found for your search<caption>");
                }
                for (let i = 0; i < data.length; i++) {
                    $("#table_body")
                        .after('<tr>' +
                            '<th id="non-fix-h">' + data[i]["project_pk"] + '</th>' +
                            '<th id="non-fix-h">' + data[i]["project_name"] + '</th>' +
                            '<th id="non-fix-h">' + data[i]["project_start"] + '</th>' +
                            '<th id="non-fix-h">' + data[i]["project_end"] + '</th>' +
                            '</tr>'
                        );
                }
            }
        });
    });
</script> {% endblock %}

project/ctsp/templates/ctsp/login.html
{% extends 'ctsp/base.html' %}
{% load staticfiles %}
{% block title_block %}
    Login - CTSP
{% endblock %}

{% block body_block %}
<div class="container">
    <form class="form-signin" role="form" action="{% url 'ctsp:login' %}" method="post">

        {% csrf_token %}

        <h2 class="form-signin-heading">Login</h2>

        <input type="text" id="id_username" name="username" class="form-control" placeholder="Nome" required>

        <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required>

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>

        <input type="hidden" name="next" value="{{ next }}" />

        {% if form.errors %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                Por favor, verifique o Email e/ou Senha informados
            </div>
        {% endif %}

        <a href="{% url 'ctsp:register_user' %}">registre-se</a>

    </form>
</div>
{% endblock %}

project/ctsp/templates/ctsp/welcome_login.html
{% extends 'ctsp/base.html' %}
{% load staticfiles %}
{% block title_block %}
Welcome! - CTSP
{% endblock %}

{%block body_block%}
<h1>Select your project below:</h1>

<form id="project_select_form" name="project_select_form" action="{% url 'ctsp:goto_product_backlog' %}" method="post">
    {% csrf_token %}
    <p>
        Project Name:
        <select id="select_project_pk" name="select_project_pk">
            {% for field in view.projects %}
            <option value="{{field.pk}}">{{field.project_name}}</option>
            {%endfor%}
        </select>
    </p>
    <input name="_product" type="submit" form="project_select_form" value="Go To Product Backlog!">
    <input name="_team" type="submit" form="project_select_form" value="Go To Team Management!">
</form>
{%endblock%}